version: '3.7'

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificate.crt:/etc/nginx/certificate.crt
      - ./nginx/privateKey.key:/etc/nginx/privateKey.key
    ports:
      - "3050:80"
      - "3051:443"
    # restart: always
  
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432

  testdb:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5442:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080